---
- hosts: all
  become: true
  tasks:

  - name: install packages
    ansible.builtin.package: # for different distributions
      name: 
        - "{{ apache_package }}" 
        - "{{ php_package }}" 
      state: latest
      update_cache: yes 