- hosts: all
  become: true
  tasks:

  - name: install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
# adding server roles
- hosts: all
  become: true
  roles:
    - base




