- name: Install software on Windows
  hosts: windows
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present