---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for fedora
    tags: always
    ansible.builtin.dnf:
      update_only: yes 
      update_cache: yes  
    when: ansible_distribution == "Fedora"

  - name: install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist 
      update_cache: yes  
    when: ansible_distribution == "Ubuntu"

  - name: create user
    tags: always
    ansible.builtin.user:
      name: test_user
      groups: root

  - name: add sudoers files for test_user
    tags: always
    ansible.builtin.copy:
      src: test_user_sudoer
      dest: /etc/sudoers.d/test_user
      owner: root
      group: root
      mode: 0440
  
  - name: add ssh keys for test_user
    tags: always
    ansible.builtin.authorized_key:
      user: test_user
      key: "***pub_key***"
      

- hosts: web_servers
  become: true
  tasks:
  - name: install apache on web servers (Ubuntu)
    tags: apache,ubuntu
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php7.4
    when: ansible_distribution == "Ubuntu"

  - name: install apache on web servers (Fedora)
    tags: apache,fedora
    ansible.builtin.dnf:
      name: httpd
    when: ansible_distribution == "Fedora"

  - name: ensure apache is running (Ubuntu)
    tags: apache,ubuntu
    ansible.builtin.service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache is running (Fedora)
    tags: apache,fedora
    ansible.builtin.service:
      name: httpd
      state: started
    when: ansible_distribution == "Fedora"

  - name: change email address for admin
    tags: apache,fedora
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf # Path to the file that we want to change
      regexp: '^ServerAdmin'  # The line that starts with ServerAdmin
      line: 'ServerAdmin  test@yahoo.com'  # The new line to replace the
    when: ansible_distribution == "Fedora"
    register: httpd_var
    # Task Execution: When task is executed, Ansible collects information about the task's result,
    # such as whether it was successful, if any changes were made, and any output generated by the task.
    # Storing Result: The register keyword assigns this collected information to a variable.
    # This variable can be used later in the playbook.

  -name: restart httpd (fedora)
   tags: apache,fedora
   ansible.builtin.service:
     name: httpd
     state: restarted
   when: httpd_var.changed

  - name: copy html file for site
    tags: apache,ubuntu
    ansible.builtin.copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mod: 0644

- hosts: db_servers
  tags: db,fedora
  become: true
  tasks:
  - name: install mariadb package on db servers
    ansible.builtin.dnf:
      name: mariadb
    when: ansible_distribution == "Fedora"