name: Push Docker Image and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t nimaianp75/devops_web:24.2.24 .

      - name: Push Docker image to Docker Hub
        run: docker push nimaianp75/devops_web:24.2.24

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_SERVER }}

      - name: SSH to Server and Pull Docker Image
        env:
          ip_add: ${{ secrets.IP_ADD }}
        run: |
          ssh -v -o StrictHostKeyChecking=no $ip_add 'docker pull nimaianp75/devops_web:24.2.24'

      - name: SSH to Server and Run Docker Container
        env:
          ip_add: ${{ secrets.IP_ADD }}
        run: |
          ssh -o StrictHostKeyChecking=no $ip_add 'docker run -d -p 80:80 --name port_web nimaianp75/devops_web:24.2.24'